[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npm run build"

[deploy]
startCommand = "cd server && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1